name: Fetch Latest Cloud SQL Auth Proxy Version and Send Slack Alerts

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 13 * * 1' # Runs every Monday at 7 PM IST (1:30 PM UTC)

jobs:
  Fetch_SQL_Auth_Proxy_Version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [stage, prod]  # Define the environments

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Set environment variables
        run: |
          if [ "${{ matrix.env }}" == "dev" ]; then
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_DEV }}" >> $GITHUB_ENV
          elif [ "${{ matrix.env }}" == "stage" ]; then
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_STAGE }}" >> $GITHUB_ENV
          elif [ "${{ matrix.env }}" == "prod" ]; then
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_PROD }}" >> $GITHUB_ENV
          fi

      - name: Capitalize the env name
        run: |
          echo "ENVIRONMENT=$(echo ${{ matrix.env }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV

      - name: Fetch Latest Cloud SQL Auth Proxy Version
        id: get_latest_version
        run: |
          latest_release=$(curl -s https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-proxy/releases/latest | jq -r '.tag_name')
          if [ -z "$latest_release" ]; then
            echo "Failed to fetch the latest version."
            exit 1
          fi
          echo "Latest release version: $latest_release"
          echo "LATEST_VERSION=$latest_release" >> $GITHUB_ENV

      - name: Send Slack Alert with Latest Version
        run: |
          message="The latest Cloud SQL Auth Proxy version for ${ENVIRONMENT} environment is ${{ env.LATEST_VERSION }}."
          curl -X POST -H 'Content-type: application/json' --data "{ 'text': '${message}'}" ${{ env.SLACK_WEBHOOK_URL }}

      - name: Send alert to Slack on job failure
        if: ${{ failure() }}
        run: |
          message="The workflow to fetch the latest Cloud SQL Auth Proxy version failed for ${ENVIRONMENT} environment."
          curl -X POST -H 'Content-type: application/json' --data "{ 'text': '${message}'}" ${{ env.SLACK_WEBHOOK_URL }}
