name: GCP Cloud SQL Auth Proxy Version Check and Send Slack Alerts

on:
  workflow_dispatch:
  # Uncomment below to schedule the workflow on a regular basis
  # schedule:
  #   - cron: '30 13 * * 1'  # Runs every Monday at 7 PM IST (1:30 PM UTC)

jobs:
  GCP_SQL_Auth_Proxy_Version_Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [stage]  # Define environments for stage and prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Set environment variables
        run: |
          if [ "${{ matrix.env }}" == "stage" ]; then
            echo "GCP_SERVICE_ACCOUNT_KEY=${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_STAGE }}" >> $GITHUB_ENV
            echo "GCP_PROJECT_ID=${{ secrets.GCLOUD_STAGE_PROJECT_ID }}" >> $GITHUB_ENV
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_STAGE }}" >> $GITHUB_ENV
          elif [ "${{ matrix.env }}" == "prod" ]; then
            echo "GCP_SERVICE_ACCOUNT_KEY=${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_PROD }}" >> $GITHUB_ENV
            echo "GCP_PROJECT_ID=${{ secrets.GCLOUD_PROJECT_ID_PROD }}" >> $GITHUB_ENV
            echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL_PROD }}" >> $GITHUB_ENV
          fi

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project ${{ env.GCP_PROJECT_ID }}

      - name: Capitalize the environment name
        run: |
          environment=$(echo ${{ matrix.env }} | tr '[:lower:]' '[:upper:]')
          echo "environment=${environment}" >> $GITHUB_ENV

      - name: Fetch Cloud SQL Auth Proxy version from instances
        run: |
          fetch_sql_auth_proxy_version() {
              local instance_name=$1
              local zone=$2
              sql_proxy_version=$(gcloud compute instances describe "$instance_name" --zone="$zone" --format="value(metadata.items.startup-script)" | grep -oP 'v\d+\.\d+\.\d+')

              if [ -z "$sql_proxy_version" ]; then
                  echo "Warning: No Cloud SQL Auth Proxy version found for instance $instance_name in $zone."
                  return
              fi

              echo "$instance_name,$zone,$sql_proxy_version" >> sql_auth_proxy_versions.txt
          }

          instances_and_zones=$(gcloud compute instances list --format="csv[no-heading](name,zone)" | grep -E 'cloud-sql-connect|.*-proxy-*')

          if [ -z "$instances_and_zones" ]; then
              echo "Warning: No instances found matching criteria."
              exit 0  # Exit without error
          fi

          echo "[" > sql_auth_proxy_versions.json

          while IFS=, read -r instance_name zone; do
              fetch_sql_auth_proxy_version "$instance_name" "$zone"
              if [ -f sql_auth_proxy_versions.txt ]; then
                  version=$(tail -n1 sql_auth_proxy_versions.txt | cut -d',' -f3)
                  echo "  {\"instance\": \"$instance_name\", \"zone\": \"$zone\", \"version\": \"$version\"}," >> sql_auth_proxy_versions.json
              fi
          done <<< "$instances_and_zones"

          sed -i '$ s/,$//' sql_auth_proxy_versions.json
          echo "]" >> sql_auth_proxy_versions.json

          if [ -f sql_auth_proxy_versions.json ]; then
              echo "SQL Auth Proxy versions fetched."
              cat sql_auth_proxy_versions.json
          else
              echo "Warning: No SQL Auth Proxy versions found."
          fi

      - name: Fetch the latest Cloud SQL Auth Proxy version
        id: get_latest_version
        run: |
          latest_version=$(curl -s https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-proxy/releases/latest | jq -r '.tag_name')
          echo "Latest Cloud SQL Auth Proxy version: $latest_version"
          echo "LATEST_VERSION=$latest_version" >> $GITHUB_ENV

      - name: Compare versions and send Slack alerts if updates are needed
        run: |
          latest_version="${{ env.LATEST_VERSION }}"
          versions=$(cat sql_auth_proxy_versions.json)
          update_needed=false

          for row in $(echo "${versions}" | jq -r '.[] | @base64'); do
              _jq() {
                  echo ${row} | base64 --decode | jq -r ${1}
              }

              instance=$(_jq '.instance')
              zone=$(_jq '.zone')
              current_version=$(_jq '.version')

              if [ "$current_version" != "$latest_version" ]; then
                  update_needed=true
                  message="Instance: $instance in $zone is using an outdated Cloud SQL Auth Proxy version ($current_version). Latest version is $latest_version."
                  curl -X POST -H 'Content-type: application/json' --data "{ 'text': 'GCP_SQL_AUTH_PROXY_VERSION_CHECK:\n\n$message'}" "${{ env.SLACK_WEBHOOK_URL }}"
              else
                  echo "Instance $instance in $zone is using the latest version."
              fi
          done

          if [ "$update_needed" = false ]; then
              echo "All instances are up to date."
          fi

      - name: Send alert to Slack on job failure
        if: ${{ failure() }}
        run: |
          message="The workflow for Cloud SQL Auth Proxy version check failed in the ${{ env.environment }} environment."
          curl -X POST -H 'Content-type: application/json' --data "{ 'text': 'GCP_SQL_AUTH_PROXY_VERSION_CHECK:\n\n$message'}" "${{ env.SLACK_WEBHOOK_URL }}"
