      - name: Check GCP Gateway Certificate Expiry using SSL certificates
        run: |
          certificate_name="stage-gateway"
          project_id="${{ secrets.GCP_PROJECT_ID_STAGE }}"

          # Fetch certificate expiration details from SSL Certificate Manager
          expiry_date=$(gcloud compute ssl-certificates describe "$certificate_name" \
            --global --format="value(expireTime)")
          # Convert the expiration date to epoch time
          expiry_date_epoch=$(date -d "$expiry_date" +%s)
          current_date_epoch=$(date +%s)

          # Calculate how many days are left until the certificate expires
          days_until_expiry=$(( (expiry_date_epoch - current_date_epoch) / 86400 ))
          echo "Days until certificate expiry: $days_until_expiry"

          # Define threshold in days (e.g., 30 days)
          expiry_threshold=30

          # Check if the certificate is expiring within the threshold
          if [[ $days_until_expiry -le $expiry_threshold ]]; then
            echo "The certificate $certificate_name will expire in $days_until_expiry days." > certificate_expiry_alert.txt
          else
            echo "The certificate $certificate_name is valid for more than $expiry_threshold days. Days left: $days_until_expiry" > certificate_expiry_alert.txt
          fi

      - name: Send Slack Alert if Certificate Expiration Detected
        run: |
          send_slack_notification() {
              local webhook_url="${{ env.SLACK_WEBHOOK_URL }}"
              local message=""

              # Always send the message whether the certificate is expiring or valid
              if [ -f certificate_expiry_alert.txt ]; then
                  message=$(cat certificate_expiry_alert.txt)
              fi

              curl -X POST -H 'Content-type: application/json' --data "{
                'text': 'GCP_GATEWAY_CERTIFICATE_STATUS:\n\n$message'
              }" $webhook_url
          }
          send_slack_notification
