      - name: Check GCP Gateway Certificate Expiry using SSL certificates
        run: |
          certificate_name="${{ env.GCP_GATEWAY_CERTIFICATE_NAME }}"
          project_id="${{ secrets.GCP_PROJECT_ID_STAGE }}"
          
          # Fetch certificate expiration details and DNS names from SSL Certificate Manager
          expiry_date=$(gcloud compute ssl-certificates describe "$certificate_name" \
            --global --format="value(expireTime)")

          dns=$(gcloud compute ssl-certificates describe "$certificate_name" \
            --global --format="value(subjectAlternativeNames)")

          # Convert the expiration date to epoch time
          expiry_date_epoch=$(date -d "$expiry_date" +%s)
          current_date_epoch=$(date +%s)
          
          # Calculate how many days are left until the certificate expires
          days_until_expiry=$(( (expiry_date_epoch - current_date_epoch) / 86400 ))
          echo "Days until certificate expiry: $days_until_expiry"
          echo "DNS Names: $dns"
          
          # Define threshold in days (e.g., 30 days)
          expiry_threshold=300
          
          # Check if the certificate is expiring within the threshold
          if [[ $days_until_expiry -le $expiry_threshold ]]; then
            echo "*Certificate Name*: $certificate_name" > certificate_expiry_alert.txt
            echo "*DNS Names*: $dns" >> certificate_expiry_alert.txt
            echo "*Expiry Date*: $expiry_date" >> certificate_expiry_alert.txt
            echo "*Days Until Expiry*: $days_until_expiry" >> certificate_expiry_alert.txt
          else
            echo "The certificate $certificate_name is valid for more than $expiry_threshold days."
          fi
