name: Fetch SQL Auth Connector Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_PLAIN }}  # Set this in GitHub Secrets
          project_id: GCP_PROJECT_ID_STAGE

      - name: Fetch Instance Templates
        id: fetch_templates
        run: |
          # Fetch all instance templates related to SQL Auth Connector
          gcloud compute instance-templates list --format="get(name)" | grep "cloudsql-auth-template" > templates.txt
          echo "Fetched templates: $(cat templates.txt)"

      - name: Get Versions
        id: get_versions
        run: |
          # Initialize a variable to store versions
          versions=""
          
          # Loop through each template and get the version
          while read -r template; do
            version=$(gcloud compute instance-templates describe "$template" --format=json | \
                      grep -oP 'storage.googleapis.com.*?v\K[0-9]+\.[0-9]+\.[0-9]+')
            if [ -n "$version" ]; then
              versions="$versions$version"$'\n'
            fi
          done < templates.txt

          # Print and save the versions
          echo "Versions found:"
          echo "$versions"
          echo "::set-output name=versions::$versions"  # Set the output for later steps

      - name: Display Versions
        run: |
          echo "Fetched SQL Auth Connector Versions:"
          echo "${{ steps.get_versions.outputs.versions }}"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.20.1
        with:
          payload: |
            {
              "channel": "#alerting",  # Replace with your Slack channel
              "text": "Fetched SQL Auth Connector Versions:\n${{ steps.get_versions.outputs.versions }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_STAGE }}  # Set this in GitHub Secrets
