name: Fetch SQL Auth Connector Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_PLAIN }}  # Set this in GitHub Secrets
          project_id: ${{ secrets.GCP_PROJECT_ID_STAGE }}  # Ensure this is a secret

      - name: Fetch Instance Templates
        id: fetch_templates
        run: |
          # Fetch all instance templates related to SQL Auth Connector
          gcloud compute instance-templates list --format="get(name)" | grep "cloudsql-auth-template" > templates.txt
          echo "Fetched templates: $(cat templates.txt)"

      - name: Get Versions
        id: get_versions
        run: |
          # Initialize a variable to store versions
          versions=""

          # Loop through each template and get the version
          while read -r template; do
            version=$(gcloud compute instance-templates describe "$template" --format=json | \
                      jq -r '.properties.metadata.items[] | select(.key=="startup-script") | .value | capture("storage.googleapis.com.*?v(?<version>[0-9]+\\.[0-9]+\\.[0-9]+)") | .version')

            if [ -n "$version" ]; then
              versions="$versions$version"$'\n'
            fi
          done < templates.txt

          # Print and save the versions
          echo "Versions found:"
          echo "$versions"
          echo "versions=$versions" >> $GITHUB_ENV  # Set the output for later steps

      - name: Display Versions
        run: |
          echo "Fetched SQL Auth Connector Versions:"
          echo "$versions"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1  # Updated to use the latest version
        with:
          payload: |
            {
              "channel": "#alerting",  # Replace with your Slack channel
              "text": "Fetched SQL Auth Connector Versions:\n${{ env.versions }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_STAGE }}  # Set this in GitHub Secrets
